strictness: veryhigh

ignore-paths:
  - .mypy_cache
  - venv
  - __pycache__
  - pymumble

mypy:
  run: false

bandit:
  run: true

dodgy:
  run: false

pylint:
  enable:
    - useless-suppression
  options:
    max-line-length: 120

pycodestyle:
  options:
    max-line-length: 120